spring:
  application:
    name: weather

  datasource:
    url: jdbc:postgresql://localhost:5432/weatherdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

session:
  duration_h: 0
  duration_m: 0
  duration_s: 10


